### ISSUE TITLE
Acerca de un re-cargador

### ISSUE THREAD

**Issue by Observatorio-de-Matematica** [emmanuelroque/pdefourier#3]
Hola

Te informo que el usuario/perfil https://github.com/psaktheeswaran (este es otro de sus perfiles https://github.com/saktheeswaranswan) ha descargado y vuelto a cargar, como de él, uno de tus repositorios (https://github.com/psaktheeswaran/Anna-university-pde-partial-differential-equations-with-wxmaxima-computer-algebra).
Si bifurcara no sería un problema, pero ha abultado su perfil de repositorios descargando los de otros usuarios y subiéndolos como si se le hubiesen ocurrido a él.
Ya he visto que ha hecho esto con otros repositorios y lo he denunciado, aunque sin respuesta hasta ahora; en cuanto a tu repositorio sería mejor que lo denuncies.

Que estés muy bien.

**Comment by emmanuelroque** [comment]
Hola,  muchas gracias por tu mensaje. No hay problema con lo que él hizo, de hecho Github detecta quienes son los contribuidores de código por el mismo sistema de Git. Además, mantuvo todos los copyright notice en los encabezados de los códigos. Como está publicado bajo la GPLv3, tiene derecho a compartir y redistribuir el código, siempre y cuando mantenga los encabezados de copyright y la licencia dentro de los archivos, pero sí los respetó. 

Te agradezco de igual forma que hayas tenido la inquietud de avisarnos sobre la situación. Que estés muy bien, un saludo.
